apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "21"
    field.cattle.io/creatorId: u-fvwjn
    field.cattle.io/publicEndpoints: "null"
  creationTimestamp: null
  generation: 1
  labels:
    cattle.io/creator: norman
    workload.user.cattle.io/workloadselector: deployment-rashma-dns
  name: rashma-dns
  selfLink: /apis/apps/v1/namespaces/rashma/deployments/dns
spec:
  progressDeadlineSeconds: 600
  replicas: 0
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-rashma-dns
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        cattle.io/timestamp: "2020-06-20T07:38:51Z"
        field.cattle.io/ports: '[[{"containerPort":53,"dnsName":"dns-hostport","hostPort":53,"kind":"HostPort","name":"udp53","protocol":"UDP","sourcePort":53},{"containerPort":53,"dnsName":"dns-hostport","hostPort":53,"kind":"HostPort","name":"tcp","protocol":"TCP","sourcePort":53}]]'
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: deployment-rashma-dns
    spec:
      containers:
      - env:
        - name: EXTRA_HOSTS
          value: rashma.ir=192.168.0.1    file.rashma.ir=192.168.0.1    rafra.ir=192.168.0.1
        image: cytopia/bind
        imagePullPolicy: IfNotPresent
        name: dns
        ports:
        - containerPort: 53
          hostPort: 53
          name: udp53
          protocol: UDP
        - containerPort: 53
          hostPort: 53
          name: tcp
          protocol: TCP
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
