apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "10"
    field.cattle.io/creatorId: u-fvwjn
    field.cattle.io/publicEndpoints: '[{"addresses":["185.165.42.193"],"port":30776,"protocol":"TCP","serviceName":"rashma:file-server-nodeport","allNodes":true},{"addresses":["185.165.42.193"],"port":30776,"protocol":"UDP","serviceName":"rashma:file-server-nodeport","allNodes":true},{"addresses":["185.165.42.193"],"port":80,"protocol":"HTTP","serviceName":"rashma:ingress-069e61b609c325e5f6a87a850af39b3d","ingressName":"rashma:rashma-file","hostname":"file.rashma.ir","path":"/","allNodes":true}]'
  creationTimestamp: null
  generation: 1
  labels:
    cattle.io/creator: norman
    workload.user.cattle.io/workloadselector: deployment-rashma-file-server
  name: file-server
  selfLink: /apis/apps/v1/namespaces/rashma/deployments/file-server
spec:
  progressDeadlineSeconds: 600
  replicas: 0
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-rashma-file-server
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        cattle.io/timestamp: "2020-06-20T07:38:51Z"
        field.cattle.io/ports: '[[{"containerPort":8080,"dnsName":"file-server-nodeport","kind":"NodePort","name":"tcp8080","protocol":"TCP","sourcePort":0},{"containerPort":8080,"dnsName":"file-server-nodeport","kind":"NodePort","name":"udp8080","protocol":"UDP","sourcePort":0}]]'
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: deployment-rashma-file-server
    spec:
      containers:
      - image: koushamad/rashma-file-server
        imagePullPolicy: Always
        name: file-server
        ports:
        - containerPort: 8080
          name: tcp8080
          protocol: TCP
        - containerPort: 8080
          name: udp8080
          protocol: UDP
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
        volumeMounts:
        - mountPath: /app/tmp/files
          name: file-tmp
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /home/rashma/application/Rashma_Docker/tmp/files
          type: DirectoryOrCreate
        name: file-tmp
status: {}
