apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "6"
    field.cattle.io/creatorId: u-fvwjn
    field.cattle.io/publicEndpoints: '[{"addresses":["185.165.42.193"],"port":30406,"protocol":"TCP","serviceName":"rashma:rabbitmq-nodeport","allNodes":true},{"addresses":["185.165.42.193"],"port":32379,"protocol":"TCP","serviceName":"rashma:rabbitmq-nodeport","allNodes":true}]'
  creationTimestamp: null
  generation: 1
  labels:
    cattle.io/creator: norman
    workload.user.cattle.io/workloadselector: deployment-rashma-rabbitmq
  name: rabbitmq
  selfLink: /apis/apps/v1/namespaces/rashma/deployments/rabbitmq
spec:
  progressDeadlineSeconds: 600
  replicas: 0
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-rashma-rabbitmq
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        cattle.io/timestamp: "2020-06-20T07:38:51Z"
        field.cattle.io/ports: '[[{"containerPort":15672,"dnsName":"rabbitmq-nodeport","kind":"NodePort","name":"tcp15672","protocol":"TCP","sourcePort":0},{"containerPort":5672,"dnsName":"rabbitmq-nodeport","kind":"NodePort","name":"tcp5672","protocol":"TCP","sourcePort":0}]]'
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: deployment-rashma-rabbitmq
    spec:
      containers:
      - env:
        - name: RABBITMQ_DEFAULT_PASS
          value: rabbitmq
        - name: RABBITMQ_DEFAULT_USER
          value: rabbitmq
        - name: RABBITMQ_NODENAME
          value: rabbitmq
        image: rabbitmq:3-management
        imagePullPolicy: Never
        name: rabbitmq
        ports:
        - containerPort: 15672
          name: tcp15672
          protocol: TCP
        - containerPort: 5672
          name: tcp5672
          protocol: TCP
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
        volumeMounts:
        - mountPath: /var/lib/rabbitmq
          name: rabbitmq
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /mnt/rabbitmq/rabbitmq
          type: DirectoryOrCreate
        name: rabbitmq
status: {}
