apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "3"
    field.cattle.io/creatorId: u-fvwjn
    field.cattle.io/publicEndpoints: '[{"addresses":["185.165.42.193"],"port":31124,"protocol":"TCP","serviceName":"rashma:redis-nodeport","allNodes":true},{"addresses":["185.165.42.193"],"port":31124,"protocol":"UDP","serviceName":"rashma:redis-nodeport","allNodes":true}]'
  creationTimestamp: null
  generation: 1
  labels:
    cattle.io/creator: norman
    workload.user.cattle.io/workloadselector: deployment-rashma-redis
  name: redis
  selfLink: /apis/apps/v1/namespaces/rashma/deployments/redis
spec:
  progressDeadlineSeconds: 600
  replicas: 0
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-rashma-redis
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        cattle.io/timestamp: "2020-06-20T07:38:51Z"
        field.cattle.io/ports: '[[{"containerPort":6379,"dnsName":"redis-nodeport","kind":"NodePort","name":"tcp6379","protocol":"TCP","sourcePort":0},{"containerPort":6379,"dnsName":"redis-nodeport","kind":"NodePort","name":"udp6379","protocol":"UDP","sourcePort":0}]]'
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: deployment-rashma-redis
    spec:
      containers:
      - image: library/redis:6.0.4
        imagePullPolicy: Always
        name: redis
        ports:
        - containerPort: 6379
          name: tcp6379
          protocol: TCP
        - containerPort: 6379
          name: udp6379
          protocol: UDP
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
