###############################################################################
#                                    RASHMA                                   #
###############################################################################
version: "3.1"
services:
    rashma-redis:
      image: library/redis:6.0.4
      container_name: 'rashma-redis'
      restart: unless-stopped
      volumes:
        - ./docker/redis/data:/data
      ports:
        - 6379:6379
      networks:
        - backend

    rashma-mysql:
      image: mysql:8.0
      container_name: rashma-mysql
      working_dir: /application
      command:
        - "--default-authentication-plugin=mysql_native_password"
      volumes:
        - ./Rashma_Laravel:/application
      environment:
        - MYSQL_ROOT_PASSWORD=rashma
        - MYSQL_DATABASE=rashma
        - MYSQL_USER=rashma
        - MYSQL_PASSWORD=rashma
      ports:
        - 3306:3306
      networks:
        - backend

    rashma-mongo:
      container_name: rashma-mongo
      image: mongo
      ports:
        - 27017:27017
      networks:
        - backend

    rashma-webserver:
      image: nginx:alpine
      container_name: rashma-webserver
      volumes:
        - ./Rashma_Laravel:/application
        - ./Rashma_Docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - 80:80
       - 433:433
      links:
        - rashma-php-fpm
      depends_on:
        - rashma-php-fpm
      networks:
        - backend

    rashma-rabbitmq:
      image: rabbitmq
      container_name: rashma-rabbit
      environment:
        RABBITMQ_DEFAULT_USER: rabbitmq
        RABBITMQ_DEFAULT_PASSWORD: rabbitmq
        RABBITMQ_DEFAULT_VHOST: /
        RABBITMQ_SSL_CACERTFILE: /rootCA.pem
        RABBITMQ_SSL_CERTFILE: /rootCA.pem
        RABBITMQ_SSL_KEYFILE: /rootCA.key
        RABBITMQ_SSL_VERIFY: verify_none
        RABBITMQ_SSL_FAIL_IF_NO_PEER_CERT: "false"
      volumes:
        - "./Rashma_Docker/rabbitmq/rootCA.pem:/rootCA.pem:ro"
        - "./Rashma_Docker/rabbitmq/rootCA.key:/rootCA.key:ro"
      ports:
        - 15671:15671
        - 15672:15672
        - 5671:5671
        - 5672:5672
      networks:
        - backend

    rashma-socketio-client-tool:
      image: amritb/socketio-client-tool:latest
      container_name: rashma-socket-client
      ports:
        - 9001:8080
      networks:
        - backend

    rashma-php-fpm:
      image: koushamad/rashma-php-fpm:latest
      build: ./Rashma_Docker/php-fpm
      container_name: rashma-php-fpm
      working_dir: /application
      volumes:
        - ./Rashma_Laravel:/application
        - ./Rashma_Docker/php-fpm/php-ini-overrides.ini:/etc/php/7.3/fpm/conf.d/99-overrides.ini
        - ./Rashma_Docker/php-fpm/crontab:/etc/cron.d/cron
      command: sh -c "./install.sh"
      links:
        - rashma-redis
        - rashma-mongo
        - rashma-mysql
      depends_on:
        - rashma-redis
        - rashma-mongo
        - rashma-mysql
      networks:
        - backend

    rashma-file-server:
      build:
        context: ./Rashma_File
        dockerfile: Dockerfile
      image: koushamad/rashma-file-server:latest
      container_name: rashma-file
      environment:
        DB_HOST: rashma-mysql
        DB_MONGO_HOST: rashma-mongo
        REDIS_HOST: rashma-reddis
      volumes:
        - ./Rashma_Docker/tmp:/app/tmp
      ports:
        - 8080:8080
      links:
        - rashma-redis
        - rashma-mongo
        - rashma-mysql
      depends_on:
        - rashma-redis
        - rashma-mongo
        - rashma-mysql
      networks:
        - backend

    rashma-socket-server:
      build:
        context: ./Rashma_Socket
        dockerfile: Dockerfile
      image: koushamad/rashma-socket-server:latest
      container_name: rashma-socket
      environment:
        DB_CONNECTION: mysql
        DB_HOST: rashma:rashma@tcp(rashma-mysql:3306)/rashma
        DB_MONGO_HOST: rashma-mongo
      ports:
        - 1000:1000
      links:
        - rashma-redis
        - rashma-mongo
        - rashma-mysql
      depends_on:
        - rashma-redis
        - rashma-mongo
        - rashma-mysql
      networks:
        - backend

    rashma-git-server:
      build:
        context: .
        dockerfile: Dockerfile
      image: koushamad/rashma-git-server:latest
      container_name: rashma-git
      working_dir: /application
      volumes:
        - .:/application
      command: sh -c "./upddate.sh"
      networks:
        - backend

networks:
  backend: