###############################################################################
#                                    RASHMA                                   #
###############################################################################
version: "3.1"
services:
    rashma-redis:
      image: library/redis:6.0.4
      container_name: 'rashma-redis'
      restart: unless-stopped
      volumes:
        - ./Rashma_Docker/redis/data:/data
      ports:
        - 6379:6379
      networks:
        - backend

    rashma-mysql:
      image: mysql:5.7.29
      container_name: rashma-mysql
      restart: unless-stopped
      working_dir: /application
      tty: true
      volumes:
        - ./Rashma-Docker/mysql/data/:/var/lib/mysql/
        - ./Rashma-Docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      environment:
        MYSQL_DATABASE: ${DB_DATABASE}
        MYSQL_USER: ${DB_USERNAME}
        MYSQL_PASSWORD: ${DB_PASSWORD}
        MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      ports:
        - 3306:3306
      networks:
        - backend

    rashma-mongo:
      image: mongo:3.6.18
      container_name: rashma-mongo
      restart: unless-stopped
      volumes:
        - ./Rashma-Docker/mongo/data:/data
        - ./Rashma-Docker/mongo/log:/var/log/mongodb
      ports:
        - 27017:27017
      networks:
        - backend

    rashma-webserver:
      image: nginx:alpine
      container_name: rashma-webserver
      restart: unless-stopped
      volumes:
        - ./Rashma_Laravel:/application
        - ./Rashma_Docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - 80:80
       - 433:433
      links:
        - rashma-php-fpm
      depends_on:
        - rashma-php-fpm
      networks:
        - backend

    rashma-rabbitmq:
      image: library/rabbitmq:3.7.5-management
      container_name: 'rashma-rabbitmq'
      environment:
        RABBITMQ_ERLANG_COOKIE: ${RABBITMQ_ERLANG_COOKIE}
        RABBITMQ_DEFAULT_USER: ${RABBIT_USER}
        RABBITMQ_DEFAULT_PASS: ${RABBIT_PASSWORD}
        RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_DEFAULT_VHOST}
      ports:
        - 15672:15672
        - 5672:5672
      networks:
        - backend

    rashma-socketio-client-tool:
      image: amritb/socketio-client-tool:latest
      container_name: rashma-socket-client
      restart: unless-stopped
      ports:
        - 8080:8080
      networks:
        - backend

    rashma-php-fpm:
      image: koushamad/rashma-php-fpm:latest
      build: ./Rashma_Docker/php-fpm
      container_name: rashma-php-fpm
      restart: unless-stopped
      working_dir: /application
      volumes:
        - ./Rashma_Laravel:/application
        - ./Rashma_Docker/php-fpm/php-ini-overrides.ini:/etc/php/7.3/fpm/conf.d/99-overrides.ini
        - ./Rashma_Docker/php-fpm/crontab:/etc/cron.d/cron
      command: sh -c "./install.sh"
      links:
        - rashma-redis
        - rashma-mongo
        - rashma-mysql
      depends_on:
        - rashma-redis
        - rashma-mongo
        - rashma-mysql
      ports:
        - 9000:9000
      networks:
        - backend

    rashma-file-server:
      build:
        context: ./Rashma_File
        dockerfile: Dockerfile
      image: koushamad/rashma-file-server:latest
      container_name: rashma-file
      restart: unless-stopped
      environment:
        DB_HOST: rashma-mysql
        DB_MONGO_HOST: rashma-mongo
        REDIS_HOST: rashma-reddis
      volumes:
        - ./Rashma_Docker/tmp:/app/tmp
      ports:
        - 8000:8000
      links:
        - rashma-redis
        - rashma-mongo
        - rashma-mysql
      depends_on:
        - rashma-redis
        - rashma-mongo
        - rashma-mysql
      networks:
        - backend

    rashma-socket-server:
      build:
        context: ./Rashma_Socket
        dockerfile: Dockerfile
      image: koushamad/rashma-socket-server:latest
      container_name: rashma-socket
      restart: unless-stopped
      environment:
        DB_CONNECTION: mysql
        DB_HOST: rashma:rashma@tcp(rashma-mysql:3306)/rashma
        DB_MONGO_HOST: rashma-mongo
      ports:
        - 1000:1000
      links:
        - rashma-redis
        - rashma-mongo
        - rashma-mysql
      depends_on:
        - rashma-redis
        - rashma-mongo
        - rashma-mysql
      networks:
        - backend

    rashma-git-server:
      build:
        context: .
        dockerfile: Dockerfile
      image: koushamad/rashma-git-server:latest
      container_name: rashma-git
      restart: unless-stopped
      working_dir: /application
      volumes:
        - .:/application
      command: sh -c "./upddate.sh"
      networks:
        - backend

networks:
  backend: