###############################################################################
#                                    RASHMA                                   #
###############################################################################
version: "3.1"
services:
    redis:
      image: redis:alpine
      container_name: rashma-redis

    mysql:
      image: mysql:8.0
      container_name: rashma-mysql
      working_dir: /application
      command:
        - "--default-authentication-plugin=mysql_native_password"
      volumes:
        - ./Rashma_Laravel:/application
      environment:
        - MYSQL_ROOT_PASSWORD=rashma
        - MYSQL_DATABASE=rashma
        - MYSQL_USER=rashma
        - MYSQL_PASSWORD=rashma
      ports:
        - "3306:3306"

    elasticsearch:
      image: elasticsearch:6.5.4
      container_name: rashma-elasticsearch

    php-fpm:
      build: ./Rashma_Docker/php-fpm
      container_name: rashma-php-fpm
      working_dir: /application
      volumes:
        - ./Rashma_Laravel:/application
        - ./Rashma_Docker/php-fpm/php-ini-overrides.ini:/etc/php/7.3/fpm/conf.d/99-overrides.ini
        - ./Rashma_Docker/php-fpm/crontab:/etc/cron.d/cron

    mongo:
      container_name: rashma-mongo
      image: mongo
      ports:
        - "27017:27017"

    webserver:
      image: nginx:alpine
      container_name: rashma-webserver
      working_dir: /application
      volumes:
          - ./Rashma_Laravel:/application
          - ./Rashma_Docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "80:80"
       - "433:433"

    rabbitmq:
      image: rabbitmq
      environment:
        RABBITMQ_DEFAULT_USER: rabbitmq
        RABBITMQ_DEFAULT_PASSWORD: rabbitmq
        RABBITMQ_DEFAULT_VHOST: /
        RABBITMQ_SSL_CACERTFILE: /rootCA.pem
        RABBITMQ_SSL_CERTFILE: /rootCA.pem
        RABBITMQ_SSL_KEYFILE: /rootCA.key
        RABBITMQ_SSL_VERIFY: verify_none
        RABBITMQ_SSL_FAIL_IF_NO_PEER_CERT: "false"
      volumes:
        - "./Rashma_Docker/rabbitmq/rootCA.pem:/rootCA.pem:ro"
        - "./Rashma_Docker/rabbitmq/rootCA.key:/rootCA.key:ro"
      ports:
        - 15671:15671
        - 15672:15672
        - 5671:5671
        - 5672:5672

    netdata:
      image: netdata/netdata
      ports:
        - 19999:19999
      cap_add:
        - SYS_PTRACE
      security_opt:
        - apparmor:unconfined
      volumes:
        - /proc:/host/proc:ro
        - /sys:/host/sys:ro
        - /var/run/docker.sock:/var/run/docker.sock:ro

    file-server:
      build:
        context: ./Rashma_File
        dockerfile: Dockerfile
      volumes:
        - ./Rashma_Docker/tmp:/app/tmp
      ports:
        - "8080:8080"
    
    socket-server:
      build:
        context: ./Rashma_Socket
        dockerfile: Dockerfile
      ports:
        - "9000:9000"

    socketio-client-tool:
      image: amritb/socketio-client-tool:latest
      ports:
        - "9001:8080"