apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-deploy.yaml --out ./Rashma_Docker/k8s
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: rashma-redis
  name: rashma-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: rashma-redis
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose-deploy.yaml --out ./Rashma_Docker/k8s
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.network/backend: "true"
        io.kompose.service: rashma-redis
    spec:
      containers:
      - image: library/redis:6.0.4
        imagePullPolicy: ""
        name: rashma-redis
        ports:
        - containerPort: 6379
        resources: {}
        volumeMounts:
        - mountPath: /data
          name: rashma-redis-claim0
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: rashma-redis-claim0
        persistentVolumeClaim:
          claimName: rashma-redis-claim0
status: {}
