apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-deploy.yaml --out ./Rashma_Docker/k8s
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: rashma-socket-server
  name: rashma-socket-server
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: rashma-socket-server
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose-deploy.yaml --out ./Rashma_Docker/k8s
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.network/backend: "true"
        io.kompose.service: rashma-socket-server
    spec:
      containers:
      - env:
        - name: DB_CONNECTION
          value: mysql
        - name: DB_HOST
          value: rashma:rashma@tcp(rashma-mysql:3306)/rashma
        - name: DB_MONGO_HOST
          value: rashma-mongo
        image: koushamad/rashma-socket-server:latest
        imagePullPolicy: ""
        name: rashma-socket
        ports:
        - containerPort: 1000
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
