apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-deploy.yaml --out ./Rashma_Docker/k8s
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: socket-server
  name: socket-server
spec:
  ports:
  - name: "9001"
    port: 9001
    targetPort: 9000
  selector:
    io.kompose.service: socket-server
status:
  loadBalancer: {}
