apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-deploy.yaml --out ./Rashma_Docker/k8s
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: socketio-client-tool
  name: socketio-client-tool
spec:
  ports:
  - name: "9002"
    port: 9002
    targetPort: 8080
  selector:
    io.kompose.service: socketio-client-tool
status:
  loadBalancer: {}
