name: RELESE

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      - name: Build the docker-compose stack
        run: docker-compose --log-level INFO up -d --build
      - name: Push rashma-php-fpm
        run: docker push koushamad/rashma-php-fpm:0.0.3
      - name: Push rashma-file-server
        run: docker push koushamad/rashma-file-server:0.0.3
      - name: Push rashma-socket-server
        run: docker push koushamad/rashma-socket-server:0.0.3
      - name: Push rashma-git-server
        run: docker push koushamad/rashma-git-server:0.0.3