name: RELESE

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: koushamad/Rashma@master
      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      - name: Build the docker-compose stack
        run: docker-compose -f docker-compose.yml up -d
      - name: Push rashma-php-fpm
        run: docker push koushamad/rashma-php-fpm:latest
      - name: Push rashma-file-server
        run: docker push koushamad/rashma-file-server:latest
      - name: Push rashma-socket-server
        run: docker push koushamad/rashma-socket-server:latest
      - name: Push rashma-git-server
        run: docker push koushamad/rashma-git-server:latest

  Deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: sekassel-research/actions-rancher-update@1.0.0
        with:
          rancher_url: https://dashboard.docker.host/v3
          rancher_access: ${{ secrets.RANCHER_ACCESS }}
          rancher_key: ${{ secrets.RANCHER_KEY }}
          project_id: rashma
          stack_name: rashma
          service_name: rashma-php-fpm
          docker_image: koushamad/rashma-php-fpm:latest
      - uses: sekassel-research/actions-rancher-update@1.0.0
        with:
          rancher_url: https://dashboard.docker.host/v3
          rancher_access: ${{ secrets.RANCHER_ACCESS }}
          rancher_key: ${{ secrets.RANCHER_KEY }}
          project_id: rashma
          stack_name: rashma
          service_name: rashma-file-server
          docker_image: koushamad/rashma-file-server:latest
      - uses: sekassel-research/actions-rancher-update@1.0.0
        with:
          rancher_url: https://dashboard.docker.host/v3
          rancher_access: ${{ secrets.RANCHER_ACCESS }}
          rancher_key: ${{ secrets.RANCHER_KEY }}
          project_id: rashma
          stack_name: rashma
          service_name: rashma-git-server
          docker_image: koushamad/rashma-git-server:latest
      - uses: sekassel-research/actions-rancher-update@1.0.0
        with:
          rancher_url: https://dashboard.docker.host/v3
          rancher_access: ${{ secrets.RANCHER_ACCESS }}
          rancher_key: ${{ secrets.RANCHER_KEY }}
          project_id: rashma
          stack_name: rashma
          service_name: rashma-socket-server
          docker_image: koushamad/rashma-socket-server:latest